# Site settings
title: The Gaming Puma
email: gamingpuma13@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Full Sail University student, video game blogger, and the best medic you'll find on any virtual field.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: pumaomega
github_username:  SorensenAndrew
date: 1/6/15
# Build settings
markdown: kramdown
